import Head from 'next/head';

export default function Home() {
    return (
        <>
            <Head>
                <title>Tukky Portfolio</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <img className="w-full h-[500px] object-cover" src="/images/top.jpg" alt="夜の月の画像" />
                <div className='w-2/3 m-auto'>
                    <div className='my-6'>
                        <h2 className='text-center text-2xl mb-4'>PROFILE</h2>
                        <h2 className='text-center text-2xl mb-4'>WORKS</h2>
                        <div className='grid grid-cols-1 sm:grid-cols-3 gap-10'>
                            <div className='border'>半年に一度の食事会</div>
                            <div className='border'>Tukky Note</div>
                            <div className='border'>Tukky Lab</div>
                        </div>
                        <h2 className='text-center text-2xl mb-4'>SKILL</h2>
                        <div className='grid grid-cols-1 sm:grid-cols-3 gap-10'>
                            <div className='border'>フロントエンド</div>
                            <div className='border'>バックエンド</div>
                            <div className='border'>サーバ・インフラ</div>
                        </div>
                    </div>
                </div>
                <footer className='w-full bg-gray-500 text-white text-center leading-6'><small>&copy; 2023 tukky</small></footer>
            </main>
        </>
    );
}
