import Head from 'next/head';
import { Inter } from '@next/font/google';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
    return (
        <>
            <Head>
                <title>Portfolio</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <div className="w-full p-2 text-4xl fixed bg-gray-100">Tukky's Portfolio</div>
                <img className="w-full h-[500px] object-cover pt-14" src="/images/top.jpg" alt="夜の月の画像" />
                <div className='my-6'>
                    <h2 className='text-center text-2xl'>WORKS</h2>
                </div>
            </main>
        </>
    );
}
