import Head from 'next/head';

const CommonHead = () => {
    return (
        <Head>
            <title>Tukky&apos;s Portfolio</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
            <meta property="og:title" content="Tukky's Portfolio" />
            <meta property="og:description" content="ITエンジニアTukkyのポートフォリオサイトです。" />
            <meta property="og:type" content="website" />
            <meta property="og:image" content="/images/top.jpg" />
            <meta property="og:url" content="https://tukky-14.github.io/" />
        </Head>
    );
};

export default CommonHead;
